# Generated by Django 4.0.4 on 2022-10-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashsale',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
