# Generated by Django 4.0.4 on 2022-09-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashsale',
            name='body_type',
            field=models.CharField(max_length=100),
        ),
    ]
