# Generated by Django 4.0.4 on 2022-10-04 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_alter_carwashsale_body_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashsale',
            name='vehicle',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Vehicle Registration doesn't comply", regex='^[A-Z]{2,4}[0-9]{3,4}[A-Z]{1}$')]),
        ),
    ]
