repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-shebang-scripts-are-executable
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]