# Generated by Django 4.0.4 on 2022-04-28 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registration', models.CharField(max_length=10)),
                ('body_type', models.CharField(choices=[('SUV', 'SUV'), ('Saloon', 'Saloon'), ('Lorry', 'Lorry'), ('Bus', 'Bus'), ('Motorcycle', 'Motorcyle'), ('Tuktuk', 'Tuktuk'), ('Tipper', 'Tipper'), ('Van', 'Van'), ('Vehicle parts', 'Vehicle Parts')], default='Saloon', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
