# Generated by Django 4.0.4 on 2022-05-11 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carwash', '0002_rename_unique_id_vehicle_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('CANCELLED', 'Cancelled')], max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('vehicle_type', models.CharField(choices=[('SUV', 'Suv'), ('Saloon', 'Saloon'), ('Lorry', 'Lorry'), ('Bus', 'Bus'), ('Motorcyle', 'Motorcycle'), ('Tuktuk', 'Tuktuk'), ('Tipper', 'Tipper'), ('Van', 'Van'), ('Parts', 'Parts')], max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='body_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('SUV', 'Suv'), ('Saloon', 'Saloon'), ('Lorry', 'Lorry'), ('Bus', 'Bus'), ('Motorcyle', 'Motorcycle'), ('Tuktuk', 'Tuktuk'), ('Tipper', 'Tipper'), ('Van', 'Van'), ('Parts', 'Parts')], default='Saloon', max_length=30),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.sale')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.service')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carwash.vehicle'),
        ),
    ]
